[WIP] Add user profile document
Interacao-Humano-Computador/2020.1-BCE pull request #38
Opened 2020-09-18 17:56 UTC by durvalcarvalho

closes #24 

## Descrição
Foi feito uma pesquisa exploratória a procurando referencias bibliograficas que abordem os temas "bibliotecas universitárias", "usabilidade", "pesquisa acadêmica", "BCE", "UnB". 

Com base na leitura dos materiais encontrados, foi criado o documento de perfil de usuário, com os dados relevantes para o nosso contexto.

## Tarefas gerais realizadas
* Pesquisa e Seleção de trabalhos realizados que tem como escopo os usuários dos sistemas da BCE
* Leitura e sumarização dos trabalhos selecionados
* Elaboração do documento de perfil de usuário com os dados relevantes

2020-09-18 17:59 UTC, durvalcarvalho commented
O único documento que precisa ser revisado é o `user_profile.md`. Os documentos de `relatorio-*-user-profile-search.md` serviram de suporte ao documento principal e não estaram visíveis no github pages.

2020-09-18 17:59 UTC, durvalcarvalho commented
Para fechar esse PR é preciso que o Geraldo suba as modificações dele.

2020-09-18 19:04 UTC, RafaellaJunqueira commented
> Não feche esse PR enquanto o @geraldovictor não subir as modificações dele.

2020-09-18 21:46 UTC, RafaellaJunqueira requested changes
Eu vi que no documento existe uma parte para inserir as personas. Acho melhor tirar, deixar as personas como um documento separado, esse já está bem grande.

2020-09-22 13:51 UTC, durvalcarvalho commented
@RafaellaJunqueira  As correções foram feitas. As informações obtidas pela pesquisa realizada pelo @geraldovictor foram adcionadas ao documento `ùser_profile.md`

2020-09-22 15:01 UTC, merged