Add interviews
Interacao-Humano-Computador/2020.1-BCE pull request #90
Opened 2020-10-15 15:18 UTC by durvalcarvalho

closes #76

## Descrição

Adição das entrevistas realizadas

## Tarefas gerais realizadas
* Foi encontrado participantes aptos
* Foi agendado um data para a entrevista
* Foi realizado a entrevista
* O vídeo gerado foi editado e subido para o Youtube
* Foi gerado um documento das entrevistas

2020-10-15 22:12 UTC, RafaellaJunqueira requested changes
### Esse ponto de metodologia não é necessário, já foi descrito no documento de planejamento. Acho que vc pode fundir a introdução e o objetivo como um único tópico, tipo "contexto" ou algo assim. A conclusão tmb pode ser só um indicativo pro resultado da coleta que é a análise de tarefas - parte 2, não? Esse doc é só pra documentar mesmo as entrevistas, bem coleta de dados mesmo.

2020-10-15 22:40 UTC, durvalcarvalho commented
> Esse ponto de metodologia não é necessário, já foi descrito no documento de planejamento. Acho que vc pode fundir a introdução e o objetivo como um único tópico, tipo "contexto" ou algo assim. A conclusão tmb pode ser só um indicativo pro resultado da coleta que é a análise de tarefas - parte 2, não? Esse doc é só pra documentar mesmo as entrevistas, bem coleta de dados mesmo.

Eu acho importante manter o quarteto "_introdução/objetivo/metodologia/conclusão_" para manter a consistência dos documentos do nosso trabalho. O professor vem elogiando a nossa "_pega metodológica_" nos feedbacks e esse quarteto é fundamental para que caso alguém caia de paraquedas nesse documento, se tenha o contexto das informações que serão apresentadas.

2020-10-18 17:08 UTC, RafaellaJunqueira commented
> > Esse ponto de metodologia não é necessário, já foi descrito no documento de planejamento. Acho que vc pode fundir a introdução e o objetivo como um único tópico, tipo "contexto" ou algo assim. A conclusão tmb pode ser só um indicativo pro resultado da coleta que é a análise de tarefas - parte 2, não? Esse doc é só pra documentar mesmo as entrevistas, bem coleta de dados mesmo.
> 
> Eu acho importante manter o quarteto "_introdução/objetivo/metodologia/conclusão_" para manter a consistência dos documentos do nosso trabalho. O professor vem elogiando a nossa "_pega metodológica_" nos feedbacks e esse quarteto é fundamental para que caso alguém caia de paraquedas nesse documento, se tenha o contexto das informações que serão apresentadas.

Bom, eu acho que não precisa por seu um documento que complementa o outro e por ser o registro de algo mais prático, então me parece informação repetida sem necessidade. Mas entendi seu ponto, se quiser deixar, não vou me opor.

2020-10-18 17:09 UTC, RafaellaJunqueira approved these changes

2020-10-18 22:15 UTC, merged